dist: focal

language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
    - libyaml-dev
    - python-pygame
    - python3-pygame
    - python3-libtorrent

# command to install dependencies
install:
  # older versions of pip won't work
  - pip install -U setuptools pip
  - pip install -r requirements.txt
  - pip --version
  - "VEXT_RELOAD_HACK=1 python setup.py install"
  - vext -s

# command to run tests
script:
  # - export VEXT_DEBUG_LOG=1
  - scripts/test_virtualenv.sh
