language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  # older versions of pip won't work
  - sudo apt-get install libyaml-dev
  - pip install nose
  - pip install -U setuptools pip
  - pip install -r requirements.txt
  - pip --version
  - "VEXT_RELOAD_HACK=1 python setup.py install"
  - vext -s

# command to run tests
script:
  - which nosetests 
  - export VEXT_DEBUG_LOG=1
  - pushd tests; python -m unittest test-vext-api; popd
  #- nosetests
